//! Capture-format parity (issue #109): the agent's `events.jsonl` — `schema::Event`
//! as serde serializes it — must flow through the correlator window into the exact
//! 8-feature vectors the Python aggregator computes.
//!
//! Consumes `ml/tests/fixtures/capture_events.jsonl` (the wire format) and
//! `ml/tests/fixtures/capture_correlation_golden.jsonl` (`{pid, features}` per PID),
//! both regenerated by `ml/tests/fixtures/gen_capture_parity.py`. The Python
//! counterpart is `ml/tests/test_capture_parity.py`.
//!
//! A break here means the Rust `Event` deserialization, `EventBus`, or
//! `features::correlation` has drifted from the format the training side reads — the
//! T2 model would score vectors it never saw at training time.

use std::time::Duration;

use correlator::EventBus;
use ml::features::correlation::{FEATURE_NAMES, extract_features};
use schema::Event;

const EVENTS: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../ml/tests/fixtures/capture_events.jsonl"
));
const GOLDEN: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../ml/tests/fixtures/capture_correlation_golden.jsonl"
));

#[test]
fn vectors_match_python_aggregator() {
    // One 60 s window (matches CorrelationEngine::new and the generator): every
    // fixture event fits inside it, so no eviction and the per-PID windows agree.
    let mut bus = EventBus::new(Duration::from_secs(60));
    for line in EVENTS.lines().filter(|l| !l.trim().is_empty()) {
        // Deserializing straight into Event is half the point — it pins the wire
        // format (identity under `meta`, `daddr` a string, `file_open` tag).
        let event: Event =
            serde_json::from_str(line).expect("events.jsonl line is a schema::Event");
        bus.push(event);
    }

    let mut checked = 0;
    for line in GOLDEN.lines().filter(|l| !l.trim().is_empty()) {
        let row: serde_json::Value = serde_json::from_str(line).unwrap();
        let pid = row["pid"].as_u64().unwrap() as u32;
        let expected: Vec<f64> = row["features"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap())
            .collect();
        assert_eq!(expected.len(), FEATURE_NAMES.len());

        let got = extract_features(&bus, pid);
        for (i, name) in FEATURE_NAMES.iter().enumerate() {
            // Counts and spans are exact integers/ratios here — no float slack needed
            // beyond f32 rounding on span_s.
            assert!(
                (got[i] as f64 - expected[i]).abs() <= 1e-4,
                "pid {pid} feature `{name}` drifted: Rust={} Python={} \
                 — see ml/tests/fixtures/gen_capture_parity.py",
                got[i],
                expected[i],
            );
        }
        checked += 1;
    }
    assert!(
        checked >= 4,
        "suspicious golden file: only {checked} PID vectors"
    );
}
