//! Python/Rust golden parity test for the cmdline features.
//!
//! Consumes `ml/tests/fixtures/features_golden.jsonl`, generated by
//! `ml/tests/fixtures/gen_features_golden.py` from
//! `ml/synthaea_ml/features/cmdline.py` (the reference — Python defines the model's
//! input space at training time). The Python counterpart is
//! `ml/tests/test_features_golden.py`.
//!
//! If this breaks, `ml::features::cmdline::extract_features` has drifted from the
//! Python definition: the ONNX model would score vectors at inference time it never
//! saw during training. Fix the divergence — or, if the change is intentional,
//! regenerate the golden file AND retrain the models (see the generator's docstring).

use ml::features::cmdline::{FEATURE_NAMES, extract_features};

const GOLDEN: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../ml/tests/fixtures/features_golden.jsonl"
));

/// The golden file is f64 (Python); the Rust side computes in f32. Tolerance is loose
/// relative to f32 rounding (~1e-7) but strict relative to any real definition drift.
fn close(got: f32, expected: f64) -> bool {
    let expected32 = expected as f32;
    (got - expected32).abs() <= 1e-4 * expected32.abs().max(1.0)
}

#[test]
fn parity_with_cmdline_py() {
    let mut cases = 0;
    for line in GOLDEN.lines().filter(|l| !l.trim().is_empty()) {
        let row: serde_json::Value = serde_json::from_str(line).expect("invalid golden line");
        let cmdline = row["cmdline"].as_str().expect("cmdline field");
        let expected: Vec<f64> = row["features"]
            .as_array()
            .expect("features field")
            .iter()
            .map(|v| v.as_f64().expect("non-numeric feature"))
            .collect();
        assert_eq!(expected.len(), FEATURE_NAMES.len());

        let got = extract_features(cmdline);
        for (i, name) in FEATURE_NAMES.iter().enumerate() {
            assert!(
                close(got[i], expected[i]),
                "feature `{name}` drifted from cmdline.py for {cmdline:?}: \
                 Rust={} Python={} — see ml/tests/fixtures/gen_features_golden.py",
                got[i],
                expected[i],
            );
        }
        cases += 1;
    }
    // Guardrail: an empty or mis-pathed golden file must not pass silently.
    assert!(cases >= 20, "suspicious golden file: only {cases} cases");
}
