import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { severityColor, statusColor } from "@/lib/case-display";
import { GenerateNarrativeButton } from "@/components/GenerateNarrativeButton";
import { redirect, notFound } from "next/navigation";

interface NarrativeCitation {
  detectionId: string;
  claim: string;
}

export default async function CaseDetailPage({ params }: { params: { id: string } }) {
  const session = await auth.api.getSession();

  if (!session) {
    redirect("/login");
  }

  const tenantId = session.session.activeOrganizationId;

  if (!tenantId) {
    return (
      <div className="rounded-lg bg-yellow-50 p-4">
        <p className="text-sm text-yellow-800">
          No organization selected. Please contact your administrator.
        </p>
      </div>
    );
  }

  const case_ = await prisma.case.findFirst({
    where: { id: params.id, tenantId },
    include: { detections: { orderBy: { timestamp: "desc" } } },
  });

  if (!case_) {
    notFound();
  }

  const narrative = await prisma.caseNarrative.findFirst({
    where: { caseId: case_.id },
    orderBy: { generatedAt: "desc" },
  });

  const stale = narrative
    ? case_.detections.some((d) => d.createdAt > narrative.generatedAt)
    : false;

  const citations = (narrative?.citations as unknown as NarrativeCitation[] | null) ?? [];

  return (
    <div className="space-y-6">
      <div>
        <div className="flex items-start justify-between">
          <h2 className="text-2xl font-bold text-gray-900">{case_.title}</h2>
          <div className="flex gap-2">
            <span
              className={`px-2 py-1 rounded text-xs font-medium border ${severityColor(case_.severity)}`}
            >
              {case_.severity}
            </span>
            <span
              className={`px-2 py-1 rounded text-xs font-medium border ${statusColor(case_.status)}`}
            >
              {case_.status}
            </span>
          </div>
        </div>
        {case_.description && (
          <p className="mt-1 text-sm text-gray-600">{case_.description}</p>
        )}
      </div>

      <section className="rounded-lg border border-indigo-200 bg-indigo-50 p-4">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-semibold text-indigo-900">AI-Generated Narrative</h3>
          {narrative && <GenerateNarrativeButton caseId={case_.id} label="Regenerate" />}
        </div>

        {narrative ? (
          <div className="mt-2">
            <p className="text-xs text-indigo-700">
              Generated by {narrative.model} ({narrative.provider}) ·{" "}
              {new Date(narrative.generatedAt).toLocaleString()} · may be inaccurate — verify
              against the linked evidence below.
            </p>
            {stale && (
              <p className="mt-2 text-xs font-medium text-amber-700 bg-amber-100 border border-amber-200 rounded px-2 py-1 inline-block">
                Evidence has changed since this narrative was generated.
              </p>
            )}
            <p className="mt-3 text-sm text-gray-900 whitespace-pre-wrap">{narrative.narrative}</p>
            {citations.length > 0 && (
              <p className="mt-3 flex flex-wrap gap-1 text-xs">
                {citations.map((citation, i) => (
                  <a
                    key={`${citation.detectionId}-${i}`}
                    href={`#detection-${citation.detectionId}`}
                    title={citation.claim}
                    className="px-1.5 py-0.5 rounded bg-indigo-100 text-indigo-800 border border-indigo-200 hover:bg-indigo-200"
                  >
                    [{i + 1}]
                  </a>
                ))}
              </p>
            )}
          </div>
        ) : (
          <div className="mt-2">
            <p className="text-sm text-indigo-700">No narrative generated yet.</p>
            <div className="mt-2">
              <GenerateNarrativeButton caseId={case_.id} label="Generate narrative" />
            </div>
          </div>
        )}
      </section>

      <section>
        <h3 className="text-sm font-semibold text-gray-900 mb-2">
          Evidence ({case_.detections.length})
        </h3>
        <div className="space-y-2">
          {case_.detections.map((detection) => (
            <div
              key={detection.id}
              id={`detection-${detection.id}`}
              className="border border-gray-200 rounded-lg p-3 bg-white target:ring-2 target:ring-indigo-400"
            >
              <div className="flex justify-between items-center">
                <span className="font-mono text-sm text-gray-900">{detection.technique}</span>
                <span
                  className={`px-2 py-0.5 rounded text-xs font-medium border ${severityColor(detection.severity)}`}
                >
                  {detection.severity}
                </span>
              </div>
              <p className="mt-1 text-xs text-gray-500">
                {new Date(detection.timestamp).toLocaleString()}
              </p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
