#!/usr/bin/env bash
# Quick setup script for testing Issue #110 on Fedora VM
# This automates most of the steps from fedora-vm-test-guide.md

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

echo "=== Fedora VM Test Setup for Issue #110 ==="
echo ""

# Check if running on Fedora
if [ ! -f /etc/fedora-release ]; then
    echo "WARNING: This doesn't appear to be Fedora"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo "System info:"
cat /etc/fedora-release 2>/dev/null || echo "Not Fedora"
echo "Kernel: $(uname -r)"
echo ""

# Step 1: Check prerequisites
echo "[1/6] Checking prerequisites..."

MISSING=()
command -v cmake >/dev/null 2>&1 || MISSING+=("cmake")
command -v git >/dev/null 2>&1 || MISSING+=("git")
command -v python3 >/dev/null 2>&1 || MISSING+=("python3")
command -v cargo >/dev/null 2>&1 || MISSING+=("cargo")
command -v rustc >/dev/null 2>&1 || MISSING+=("rustc")

if [ ${#MISSING[@]} -ne 0 ]; then
    echo "Missing prerequisites: ${MISSING[*]}"
    echo ""
    echo "Install with:"
    echo "  sudo dnf groupinstall -y 'Development Tools'"
    echo "  sudo dnf install -y cmake git python3 clang llvm pkg-config openssl-devel"
    echo ""
    echo "For Rust:"
    echo "  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
    exit 1
fi

echo "✓ All prerequisites installed"
echo ""

# Step 2: Check branch
echo "[2/6] Checking git branch..."
BRANCH=$(git branch --show-current)
if [ "$BRANCH" != "feat/110-ort-static-linking" ]; then
    echo "Current branch: $BRANCH"
    echo "Expected: feat/110-ort-static-linking"
    read -p "Checkout feat/110-ort-static-linking? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git fetch origin feat/110-ort-static-linking
        git checkout feat/110-ort-static-linking
    else
        echo "Staying on $BRANCH (tests may not work correctly)"
    fi
else
    echo "✓ On correct branch: $BRANCH"
fi
echo ""

# Step 3: Check disk space
echo "[3/6] Checking disk space..."
AVAILABLE=$(df -BG . | tail -1 | awk '{print $4}' | sed 's/G//')
echo "Available space: ${AVAILABLE}G"
if [ "$AVAILABLE" -lt 15 ]; then
    echo "WARNING: Less than 15GB available"
    echo "ONNX Runtime build needs ~10-12GB"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
else
    echo "✓ Sufficient disk space"
fi
echo ""

# Step 4: Build ONNX Runtime
echo "[4/6] Building ONNX Runtime..."
if [ -d "onnxruntime/build/Linux/Release" ]; then
    echo "ONNX Runtime build directory already exists"
    read -p "Rebuild from scratch? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        ./lab/provisioning/build-onnxruntime-static.sh --clean --jobs "$(nproc)"
    else
        echo "Using existing build"
    fi
else
    ./lab/provisioning/build-onnxruntime-static.sh --jobs "$(nproc)"
fi
echo ""

# Step 5: Configure environment
echo "[5/6] Configuring environment..."

export ORT_LIB_LOCATION="$REPO_ROOT/onnxruntime/build/Linux/Release"
echo "Setting ORT_LIB_LOCATION=$ORT_LIB_LOCATION"

if [ ! -d "$ORT_LIB_LOCATION" ]; then
    echo "ERROR: ORT_LIB_LOCATION doesn't exist: $ORT_LIB_LOCATION"
    exit 1
fi

echo "Generating RUSTFLAGS..."
eval "$(./lab/provisioning/ort-static-link-flags.sh)"

FLAG_COUNT=$(echo "$RUSTFLAGS" | grep -o "static=" | wc -l)
echo "✓ Generated $FLAG_COUNT library flags"
echo ""

# Step 6: Create persistent config
echo "[6/6] Creating persistent environment config..."

CONFIG_FILE="$HOME/.bashrc_ort_test"
cat > "$CONFIG_FILE" << EOF
# ONNX Runtime static linking test environment (Issue #110)
# Generated by fedora-test-setup.sh on $(date)
export ORT_LIB_LOCATION="$REPO_ROOT/onnxruntime/build/Linux/Release"
if [ -f "$REPO_ROOT/lab/provisioning/ort-static-link-flags.sh" ]; then
    eval "\$(cd "$REPO_ROOT" && ./lab/provisioning/ort-static-link-flags.sh 2>/dev/null)"
fi
EOF

echo "✓ Created $CONFIG_FILE"
echo ""

# Summary
echo "========================================="
echo "Setup complete! ✅"
echo ""
echo "Environment configured:"
echo "  ORT_LIB_LOCATION=$ORT_LIB_LOCATION"
echo "  RUSTFLAGS: $FLAG_COUNT library flags set"
echo ""
echo "To use in future shells:"
echo "  source $CONFIG_FILE"
echo ""
echo "Next steps:"
echo "  1. Test the ml crate:"
echo "       cargo test -p ml --release"
echo ""
echo "  2. Verify static linking:"
echo "       ldd \$(find target/release/deps -name 'ml-*' -type f -executable | head -1) | grep onnx"
echo "     (should return nothing if static linking worked)"
echo ""
echo "  3. See full guide:"
echo "       cat issues/fedora-vm-test-guide.md"
echo ""
echo "========================================="
