#![no_std]
#![no_main]

use aya_ebpf::{
    helpers::{
        bpf_get_current_task, bpf_probe_read_kernel, bpf_probe_read_user, bpf_probe_read_user_buf,
        bpf_probe_read_user_str_bytes,
    },
    macros::{map, tracepoint},
    maps::RingBuf,
    programs::TracePointContext,
};
use aya_log_ebpf::{info, warn};
use sensor_linux_wire::{
    ConnectEvent, EventMeta, ExecEvent, FileOpenEvent, MAX_CMDLINE_LEN, MAX_PATH_LEN, TASK_COMM_LEN,
};

#[allow(
    dead_code,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn
)]
#[cfg(bpf_target_arch = "x86_64")]
mod vmlinux;

/// Bindings generated via `bpftool btf dump` + `bindgen -target aarch64-unknown-linux-gnu` from
/// the live BTF of an Oracle Cloud VM.Standard.A1.Flex instance (Ampere, Ubuntu 24.04, kernel
/// `6.17.0-1018-oracle`). Unlike i686, aarch64 is a 64-bit architecture
/// like x86_64: no width mismatch with the BPF registers (always 64 bits), so standard struct
/// reflection applies directly, without the raw-offset workaround needed for i686.
#[allow(
    dead_code,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn
)]
#[cfg(bpf_target_arch = "aarch64")]
mod vmlinux_aarch64;

/// Ring buffer shared with userspace for `exec` events.
#[map]
static EXEC_EVENTS: RingBuf = RingBuf::with_byte_size(256 * 1024, 0);

/// Offsets of the `sched:sched_process_exec` tracepoint (x86_64). Inherited from the standard
/// layout of kernel tracepoints: an 8-byte common header (type u16, flags u8, preempt_count
/// u8, pid i32), followed by the event-specific fields. **Validated under real conditions on
/// 2026-08-12** on the WSL2 6.6.114 kernel (pid and filename readable in the produced event
/// stream).
const FILENAME_DATA_LOC_OFFSET: usize = 8;
const PID_OFFSET: usize = 12;

/// Reads `current_task->real_parent->tgid` via safe kernel reads (`bpf_probe_read_kernel`),
/// relying on the `vmlinux::task_struct` bindings generated by `aya-tool` from **this**
/// kernel's BTF. No CO-RE relocations (`bpf_core_read!`): the offsets are therefore frozen
/// for this exact kernel, which is enough for a lab agent that does not run on a
/// heterogeneous fleet of machines.
#[cfg(bpf_target_arch = "x86_64")]
fn read_ppid() -> Option<u32> {
    let task = unsafe { bpf_get_current_task() } as *const vmlinux::task_struct;
    let real_parent: *const vmlinux::task_struct = unsafe {
        bpf_probe_read_kernel(core::ptr::addr_of!((*task).real_parent) as *const _).ok()?
    };
    let ppid: i32 = unsafe {
        bpf_probe_read_kernel(core::ptr::addr_of!((*real_parent).tgid) as *const _).ok()?
    };
    Some(ppid as u32)
}

/// Reads the full arguments (`argv`) of the process being exec'd, directly from its user
/// memory: `mm->arg_start`..`mm->arg_end` covers the argv buffer (`\0`-separated strings)
/// that the kernel places on the stack at exec time. More robust than a deferred read of
/// `/proc/{pid}/cmdline` in userspace, which would lose processes too short-lived to still be
/// alive at read time — exactly the ones an attacker benefits from making ephemeral. Returns
/// `None` for kernel threads (null `mm`) or on read failure; the caller then falls back to
/// the name of the executed binary.
#[cfg(bpf_target_arch = "x86_64")]
fn read_argv(buf: &mut [u8; MAX_CMDLINE_LEN]) -> Option<u16> {
    let task = unsafe { bpf_get_current_task() } as *const vmlinux::task_struct;
    let mm: *const vmlinux::mm_struct =
        unsafe { bpf_probe_read_kernel(core::ptr::addr_of!((*task).mm) as *const _).ok()? };
    if mm.is_null() {
        return None;
    }
    let arg_start: u64 = unsafe {
        bpf_probe_read_kernel(core::ptr::addr_of!((*mm).__bindgen_anon_1.arg_start) as *const _)
            .ok()?
    };
    let arg_end: u64 = unsafe {
        bpf_probe_read_kernel(core::ptr::addr_of!((*mm).__bindgen_anon_1.arg_end) as *const _)
            .ok()?
    };
    let len = arg_end
        .saturating_sub(arg_start)
        .min(MAX_CMDLINE_LEN as u64) as usize;
    if len == 0 {
        return None;
    }
    unsafe { bpf_probe_read_user_buf(arg_start as *const u8, &mut buf[..len]).ok()? };
    Some(len as u16)
}

/// `task_struct`/`mm_struct` offsets for the i686 target (Debian 12 Bookworm, kernel
/// `6.1.0-52-686-pae`), obtained via `pahole -C task_struct`/`pahole -C mm_struct` on
/// `/usr/lib/debug/boot/vmlinux-6.1.0-52-686-pae` (package `linux-image-6.1.0-52-686-pae-dbg`,
/// `bookworm-debug` repository). **Specific to this exact kernel**, to be
/// regenerated if the kernel changes.
///
/// Raw-offset reads rather than generated struct reflection
/// (`vmlinux::task_struct`, the approach used on x86_64 above): on the
/// `bpfel-unknown-none` target, types like `c_ulong` or pointers are fixed at 8 bytes
/// regardless of the targeted host kernel's arch (the eBPF ISA uses 64-bit registers by
/// design). Reusing bindings generated by `bindgen`/`bpftool` from the i686 BTF would
/// therefore silently break the real layout of a 32-bit `task_struct`/`mm_struct` as soon as
/// it is recompiled for `bpfel-unknown-none` — confirmed by a direct test
/// (`assert!(size_of::<aya_ebpf::cty::c_ulong>() == 4)` fails to compile). Hence the explicit
/// `u32`s here, whose size depends on no compilation-target-related type resolution.
#[cfg(bpf_target_arch = "x86")]
mod i686_offsets {
    pub const TASK_MM_OFFSET: usize = 1008;
    pub const TASK_REAL_PARENT_OFFSET: usize = 1120;
    pub const TASK_TGID_OFFSET: usize = 1112;
    pub const MM_ARG_START_OFFSET: usize = 164;
    pub const MM_ARG_END_OFFSET: usize = 168;
}

#[cfg(bpf_target_arch = "x86")]
fn read_ppid() -> Option<u32> {
    use i686_offsets::{TASK_REAL_PARENT_OFFSET, TASK_TGID_OFFSET};
    let task = unsafe { bpf_get_current_task() } as usize;
    let real_parent: u32 =
        unsafe { bpf_probe_read_kernel((task + TASK_REAL_PARENT_OFFSET) as *const u32).ok()? };
    let ppid: i32 = unsafe {
        bpf_probe_read_kernel((real_parent as usize + TASK_TGID_OFFSET) as *const i32).ok()?
    };
    Some(ppid as u32)
}

#[cfg(bpf_target_arch = "x86")]
fn read_argv(buf: &mut [u8; MAX_CMDLINE_LEN]) -> Option<u16> {
    use i686_offsets::{MM_ARG_END_OFFSET, MM_ARG_START_OFFSET, TASK_MM_OFFSET};
    let task = unsafe { bpf_get_current_task() } as usize;
    let mm: u32 = unsafe { bpf_probe_read_kernel((task + TASK_MM_OFFSET) as *const u32).ok()? };
    if mm == 0 {
        return None;
    }
    let arg_start: u32 =
        unsafe { bpf_probe_read_kernel((mm as usize + MM_ARG_START_OFFSET) as *const u32).ok()? };
    let arg_end: u32 =
        unsafe { bpf_probe_read_kernel((mm as usize + MM_ARG_END_OFFSET) as *const u32).ok()? };
    let len = arg_end
        .saturating_sub(arg_start)
        .min(MAX_CMDLINE_LEN as u32) as usize;
    if len == 0 {
        return None;
    }
    unsafe { bpf_probe_read_user_buf(arg_start as *const u8, &mut buf[..len]).ok()? };
    Some(len as u16)
}

/// aarch64 (Oracle Cloud VM.Standard.A1.Flex, kernel `6.17.0-1018-oracle`): same
/// struct-reflection approach as x86_64 (see above), just on the `vmlinux_aarch64` bindings
/// generated for this architecture — no raw-offset workaround needed (64 bits on both sides,
/// no mismatch with the BPF registers).
#[cfg(bpf_target_arch = "aarch64")]
fn read_ppid() -> Option<u32> {
    let task = unsafe { bpf_get_current_task() } as *const vmlinux_aarch64::task_struct;
    let real_parent: *const vmlinux_aarch64::task_struct = unsafe {
        bpf_probe_read_kernel(core::ptr::addr_of!((*task).real_parent) as *const _).ok()?
    };
    let ppid: i32 = unsafe {
        bpf_probe_read_kernel(core::ptr::addr_of!((*real_parent).tgid) as *const _).ok()?
    };
    Some(ppid as u32)
}

#[cfg(bpf_target_arch = "aarch64")]
fn read_argv(buf: &mut [u8; MAX_CMDLINE_LEN]) -> Option<u16> {
    let task = unsafe { bpf_get_current_task() } as *const vmlinux_aarch64::task_struct;
    let mm: *const vmlinux_aarch64::mm_struct =
        unsafe { bpf_probe_read_kernel(core::ptr::addr_of!((*task).mm) as *const _).ok()? };
    if mm.is_null() {
        return None;
    }
    let arg_start: u64 = unsafe {
        bpf_probe_read_kernel(core::ptr::addr_of!((*mm).__bindgen_anon_1.arg_start) as *const _)
            .ok()?
    };
    let arg_end: u64 = unsafe {
        bpf_probe_read_kernel(core::ptr::addr_of!((*mm).__bindgen_anon_1.arg_end) as *const _)
            .ok()?
    };
    let len = arg_end
        .saturating_sub(arg_start)
        .min(MAX_CMDLINE_LEN as u64) as usize;
    if len == 0 {
        return None;
    }
    unsafe { bpf_probe_read_user_buf(arg_start as *const u8, &mut buf[..len]).ok()? };
    Some(len as u16)
}

#[tracepoint]
pub fn sched_process_exec(ctx: TracePointContext) -> u32 {
    match try_sched_process_exec(ctx) {
        Ok(ret) => ret,
        Err(ret) => ret,
    }
}

// The eBPF stack is limited to 512 bytes. `ExecEvent` (with its `cmdline` buffer of
// `MAX_CMDLINE_LEN` bytes) is built once in place below and filled progressively (never
// duplicated into a separate local buffer), to stay under that limit.
fn try_sched_process_exec(ctx: TracePointContext) -> Result<u32, u32> {
    let pid: i32 = unsafe { ctx.read_at(PID_OFFSET).map_err(|_| 1u32)? };

    let mut event = ExecEvent {
        meta: EventMeta {
            pid: pid as u32,
            ppid: read_ppid().unwrap_or(0),
            uid: aya_ebpf::helpers::bpf_get_current_uid_gid() as u32,
            gid: (aya_ebpf::helpers::bpf_get_current_uid_gid() >> 32) as u32,
            timestamp_ns: unsafe { aya_ebpf::helpers::bpf_ktime_get_ns() },
            comm: [0u8; TASK_COMM_LEN],
        },
        cmdline: [0u8; MAX_CMDLINE_LEN],
        cmdline_len: 0,
    };

    let comm = aya_ebpf::helpers::bpf_get_current_comm().map_err(|_| 1u32)?;
    let comm_len = comm.len().min(TASK_COMM_LEN);
    event.meta.comm[..comm_len].copy_from_slice(&comm[..comm_len]);

    event.cmdline_len = if let Some(argv_len) = read_argv(&mut event.cmdline) {
        argv_len
    } else {
        // Fallback: kernel threads or user-memory read failure. The tracepoint's
        // `__data_loc char[] filename` field encodes on 32 bits: low 16 bits for the offset
        // (relative to the start of the entry), high 16 bits for the length.
        let data_loc: u32 = unsafe { ctx.read_at(FILENAME_DATA_LOC_OFFSET).map_err(|_| 1u32)? };
        let filename_offset = (data_loc & 0xffff) as usize;
        let filename_len = ((data_loc >> 16) & 0xffff) as usize;

        let copy_len = filename_len.min(MAX_CMDLINE_LEN);
        let mut i = 0usize;
        while i < copy_len {
            let byte: u8 = unsafe { ctx.read_at(filename_offset + i).map_err(|_| 1u32)? };
            if byte == 0 {
                break;
            }
            event.cmdline[i] = byte;
            i += 1;
        }
        i as u16
    };

    let Some(mut entry) = EXEC_EVENTS.reserve::<ExecEvent>(0) else {
        warn!(&ctx, "sensor-linux-ebpf: ring buffer full, dropping exec event");
        return Ok(0);
    };

    entry.write(event);
    entry.submit(0);

    info!(&ctx, "sensor-linux-ebpf: exec pid={}", pid);
    Ok(0)
}

/// Ring buffer shared with userspace for `open` events.
#[map]
static FILE_OPEN_EVENTS: RingBuf = RingBuf::with_byte_size(256 * 1024, 0);

/// Offsets of the `syscalls:sys_enter_openat` tracepoint (x86_64). Standard, stable format of
/// the `syscalls:*` subsystem (documented, unlike `sched:*` tracepoints whose layout can vary
/// more): an 8-byte common header, `__syscall_nr` (4 bytes + padding), then the syscall
/// arguments aligned on 8 bytes each — `dfd`(16), `filename`(24), `flags`(32), `mode`(40).
/// Not yet verified against `/sys/kernel/tracing/events/syscalls/sys_enter_openat/format` on
/// this machine (reading requires root) — to be confirmed before trusting the data outside
/// the lab.
///
/// Known limit: `filename` is the raw path passed by the caller, not resolved against `dfd` —
/// a path relative to a non-standard directory descriptor will appear as-is, without the
/// absolute prefix. Known accepted limitation; conformance reports it.
#[cfg(any(bpf_target_arch = "x86_64", bpf_target_arch = "aarch64"))]
const OPENAT_FILENAME_PTR_OFFSET: usize = 24;
#[cfg(any(bpf_target_arch = "x86_64", bpf_target_arch = "aarch64"))]
const OPENAT_FLAGS_OFFSET: usize = 32;

/// On i686, no padding between arguments (all 4-byte `int`s/pointers, packed
/// consecutively): `dfd`(12), `filename`(16), `flags`(20), `mode`(24) — verified on
/// 2026-08-19 via `/sys/kernel/debug/tracing/events/syscalls/sys_enter_openat/format` on the
/// target i686 kernel (Debian 12 Bookworm, `6.1.0-52-686-pae`). Unlike x86_64 above, the raw
/// value at this offset occupies 4 bytes, not 8 — see the `u32` read below.
#[cfg(bpf_target_arch = "x86")]
const OPENAT_FILENAME_PTR_OFFSET: usize = 16;
#[cfg(bpf_target_arch = "x86")]
const OPENAT_FLAGS_OFFSET: usize = 20;

#[tracepoint]
pub fn sys_enter_openat(ctx: TracePointContext) -> u32 {
    match try_sys_enter_openat(ctx) {
        Ok(ret) => ret,
        Err(ret) => ret,
    }
}

fn try_sys_enter_openat(ctx: TracePointContext) -> Result<u32, u32> {
    #[cfg(any(bpf_target_arch = "x86_64", bpf_target_arch = "aarch64"))]
    let filename_ptr: u64 = unsafe { ctx.read_at(OPENAT_FILENAME_PTR_OFFSET).map_err(|_| 1u32)? };
    #[cfg(bpf_target_arch = "x86")]
    let filename_ptr: u64 = unsafe {
        ctx.read_at::<u32>(OPENAT_FILENAME_PTR_OFFSET)
            .map_err(|_| 1u32)? as u64
    };

    #[cfg(any(bpf_target_arch = "x86_64", bpf_target_arch = "aarch64"))]
    let flags: i64 = unsafe { ctx.read_at(OPENAT_FLAGS_OFFSET).map_err(|_| 1u32)? };
    #[cfg(bpf_target_arch = "x86")]
    let flags: i64 = unsafe { ctx.read_at::<i32>(OPENAT_FLAGS_OFFSET).map_err(|_| 1u32)? as i64 };

    let mut event = FileOpenEvent {
        meta: EventMeta {
            pid: (aya_ebpf::helpers::bpf_get_current_pid_tgid() >> 32) as u32,
            ppid: read_ppid().unwrap_or(0),
            uid: aya_ebpf::helpers::bpf_get_current_uid_gid() as u32,
            gid: (aya_ebpf::helpers::bpf_get_current_uid_gid() >> 32) as u32,
            timestamp_ns: unsafe { aya_ebpf::helpers::bpf_ktime_get_ns() },
            comm: [0u8; TASK_COMM_LEN],
        },
        path: [0u8; MAX_PATH_LEN],
        path_len: 0,
        flags: flags as u32,
    };

    let comm = aya_ebpf::helpers::bpf_get_current_comm().map_err(|_| 1u32)?;
    let comm_len = comm.len().min(TASK_COMM_LEN);
    event.meta.comm[..comm_len].copy_from_slice(&comm[..comm_len]);

    if filename_ptr != 0 {
        if let Ok(path) =
            unsafe { bpf_probe_read_user_str_bytes(filename_ptr as *const u8, &mut event.path) }
        {
            event.path_len = path.len() as u16;
        }
    }

    let Some(mut entry) = FILE_OPEN_EVENTS.reserve::<FileOpenEvent>(0) else {
        warn!(&ctx, "sensor-linux-ebpf: ring buffer full, dropping open event");
        return Ok(0);
    };

    entry.write(event);
    entry.submit(0);

    Ok(0)
}

/// Ring buffer shared with userspace for `connect` events.
#[map]
static CONNECT_EVENTS: RingBuf = RingBuf::with_byte_size(256 * 1024, 0);

/// Offsets of the `syscalls:sys_enter_connect` tracepoint (x86_64). Same stable layout as
/// `sys_enter_openat` (see above): 8-byte common header, `__syscall_nr`, then the arguments
/// aligned on 8 bytes each — `fd`(16), `uservaddr`(24), `addrlen`(32). Not verified against
/// `/sys/kernel/tracing/events/syscalls/sys_enter_connect/format` on this machine (reading
/// requires root) — to be confirmed before trusting the data outside the lab.
#[cfg(any(bpf_target_arch = "x86_64", bpf_target_arch = "aarch64"))]
const CONNECT_USERVADDR_PTR_OFFSET: usize = 24;

/// On i686, `fd`(12), `uservaddr`(16), `addrlen`(20) are packed without padding (the
/// `uservaddr` pointer is 4 bytes, not 8) — verified on 2026-08-19 via
/// `/sys/kernel/debug/tracing/events/syscalls/sys_enter_connect/format` on the target i686
/// kernel (Debian 12 Bookworm, `6.1.0-52-686-pae`).
#[cfg(bpf_target_arch = "x86")]
const CONNECT_USERVADDR_PTR_OFFSET: usize = 16;

/// `sa_family_t` values (linux/socket.h) for the two tracked families. Any other family
/// (notably `AF_UNIX` = 1, very frequent — D-Bus, local sockets) is ignored: out of scope of
/// the threat model (outbound network connections only).
const AF_INET: u16 = 2;
const AF_INET6: u16 = 10;

#[tracepoint]
pub fn sys_enter_connect(ctx: TracePointContext) -> u32 {
    match try_sys_enter_connect(ctx) {
        Ok(ret) => ret,
        Err(ret) => ret,
    }
}

fn try_sys_enter_connect(ctx: TracePointContext) -> Result<u32, u32> {
    #[cfg(any(bpf_target_arch = "x86_64", bpf_target_arch = "aarch64"))]
    let uservaddr_ptr: u64 = unsafe {
        ctx.read_at(CONNECT_USERVADDR_PTR_OFFSET)
            .map_err(|_| 1u32)?
    };
    #[cfg(bpf_target_arch = "x86")]
    let uservaddr_ptr: u64 = unsafe {
        ctx.read_at::<u32>(CONNECT_USERVADDR_PTR_OFFSET)
            .map_err(|_| 1u32)? as u64
    };
    if uservaddr_ptr == 0 {
        return Ok(0);
    }

    // `sockaddr.sa_family` is the first field (u16), common to all the variants
    // (sockaddr_in, sockaddr_in6, sockaddr_un...).
    let family: u16 = match unsafe { bpf_probe_read_user(uservaddr_ptr as *const u16) } {
        Ok(f) => f,
        Err(_) => return Ok(0),
    };
    if family != AF_INET && family != AF_INET6 {
        return Ok(0);
    }

    let mut event = ConnectEvent {
        meta: EventMeta {
            pid: (aya_ebpf::helpers::bpf_get_current_pid_tgid() >> 32) as u32,
            ppid: read_ppid().unwrap_or(0),
            uid: aya_ebpf::helpers::bpf_get_current_uid_gid() as u32,
            gid: (aya_ebpf::helpers::bpf_get_current_uid_gid() >> 32) as u32,
            timestamp_ns: unsafe { aya_ebpf::helpers::bpf_ktime_get_ns() },
            comm: [0u8; TASK_COMM_LEN],
        },
        daddr_v4: [0u8; 4],
        daddr_v6: [0u8; 16],
        dport: 0,
        is_ipv6: family == AF_INET6,
    };

    let comm = aya_ebpf::helpers::bpf_get_current_comm().map_err(|_| 1u32)?;
    let comm_len = comm.len().min(TASK_COMM_LEN);
    event.meta.comm[..comm_len].copy_from_slice(&comm[..comm_len]);

    // `sin_port`/`sin6_port`: same offset (2) in both structs, in network byte order
    // (big-endian) — hence the `from_be`.
    let port_be: u16 =
        unsafe { bpf_probe_read_user((uservaddr_ptr + 2) as *const u16).map_err(|_| 1u32)? };
    event.dport = u16::from_be(port_be);

    if family == AF_INET {
        // sockaddr_in::sin_addr at offset 4. Read as raw bytes ([u8; 4]), not as u32: a
        // `bpf_probe_read_user::<u32>` interprets the bytes in native endianness (LE on
        // x86_64), which reverses the address's byte order when displayed (bug observed under
        // real conditions on 2026-08-13: 127.0.0.11 displayed as "11.0.0.127").
        event.daddr_v4 = unsafe {
            bpf_probe_read_user((uservaddr_ptr + 4) as *const [u8; 4]).map_err(|_| 1u32)?
        };
    } else {
        // sockaddr_in6::sin6_addr at offset 8 (after sin6_family, sin6_port, sin6_flowinfo).
        event.daddr_v6 = unsafe {
            bpf_probe_read_user((uservaddr_ptr + 8) as *const [u8; 16]).map_err(|_| 1u32)?
        };
    }

    let Some(mut entry) = CONNECT_EVENTS.reserve::<ConnectEvent>(0) else {
        warn!(&ctx, "sensor-linux-ebpf: ring buffer full, dropping connect event");
        return Ok(0);
    };

    entry.write(event);
    entry.submit(0);

    info!(&ctx, "sensor-linux-ebpf: connect pid={}", event.meta.pid);
    Ok(0)
}

#[cfg(not(test))]
#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}

#[unsafe(link_section = "license")]
#[unsafe(no_mangle)]
static LICENSE: [u8; 13] = *b"Dual MIT/GPL\0";
