"""Reference implementation of tree-ensemble path attribution — the Python side of the
attribution parity seam.

Mirror of `crates/ml/src/forest.rs` (same definition, independent implementation and
independent ONNX parsing — the `onnx` package here, a minimal protobuf walker in Rust).

Semantics: Saabas-style path attribution over **effective depth**, the quantity the
isolation score is a monotone function of. A leaf's value is `depth + c(n)`, where `n`
is the number of training samples that reached the leaf (from the sample-count
LabelEncoder skl2onnx pairs with each tree) and `c` is sklearn's average path length
of an unbuilt subtree. Internal nodes get the sample-count-weighted expectation of
the leaf values below them; each split's move of that expectation is charged to the
split's feature. Per-feature sums are averaged over trees and negated, so positive
pushes toward anomalous. Per tree the decomposition telescopes exactly:
`leaf value = root expectation + sum(moves)`. Models without a sample-count encoder
fall back to uniform leaf weights and no `c(n)` term.

The two sides are pinned against each other by
`crates/ml/tests/fixtures/attribution_golden.json`, regenerated by
`fixtures/gen_attribution_fixture.py`. Any semantic change here is a change to the
seam: regenerate the fixture and expect the Rust side to fail until it matches.

Requires `onnx` and `numpy` (not part of the package's base dependencies yet — the
pytest skips without them).
"""

import math
from dataclasses import dataclass

import numpy as np
import onnx

_EULER_GAMMA = 0.5772156649015329


def average_path_length(n: float) -> float:
    """sklearn's `_average_path_length` for a single value."""
    if n <= 1.0:
        return 0.0
    if n == 2.0:
        return 1.0
    return 2.0 * (math.log(n - 1.0) + _EULER_GAMMA) - 2.0 * (n - 1.0) / n


@dataclass
class _Tree:
    # Parallel arrays indexed by node id; node 0 is the root.
    feature: list[int]  # original input column (Gather mapping applied); -1 for leaves
    threshold: list[float]
    true_child: list[int]
    false_child: list[int]
    is_leaf: list[bool]
    expected: list[float]


@dataclass
class Forest:
    trees: list[_Tree]
    n_features: int


def _attr_map(node: onnx.NodeProto) -> dict[str, onnx.AttributeProto]:
    return {a.name: a for a in node.attribute}


def _column_mapping(graph: onnx.GraphProto, tree_node: onnx.NodeProto) -> list[int] | None:
    """Resolves how a TreeEnsembleRegressor's feature ids map to input columns."""
    source = tree_node.input[0]
    if source in {i.name for i in graph.input}:
        return None
    producers = [n for n in graph.node if n.output and n.output[0] == source]
    if len(producers) != 1 or producers[0].op_type != "Gather":
        raise ValueError(f"unsupported producer for tree input {source!r}")
    indices_name = producers[0].input[1]
    for init in graph.initializer:
        if init.name == indices_name:
            return [int(v) for v in onnx.numpy_helper.to_array(init).reshape(-1)]
    raise ValueError(f"Gather indices {indices_name!r} are not an initializer")


def _leaf_encoders(graph: onnx.GraphProto, tree_node: onnx.NodeProto):
    """The LabelEncoders hanging off the tree's output via Cast: (keys, values) pairs."""
    encoders = []
    out = tree_node.output[0]
    casts = [n for n in graph.node if n.op_type == "Cast" and out in n.input]
    for cast in casts:
        for enc in graph.node:
            if enc.op_type == "LabelEncoder" and cast.output[0] in enc.input:
                attrs = _attr_map(enc)
                encoders.append(
                    (list(attrs["keys_int64s"].ints), list(attrs["values_floats"].floats))
                )
    return encoders


def _structure(tree: _Tree) -> tuple[list[int], list[int]]:
    """Depth per node and a parent-before-children visit order (root = node 0)."""
    count = len(tree.feature)
    depth = [0] * count
    order = []
    stack = [0]
    while stack:
        node = stack.pop()
        order.append(node)
        if not tree.is_leaf[node]:
            for child in (tree.true_child[node], tree.false_child[node]):
                depth[child] = depth[node] + 1
                stack.append(child)
    if len(order) != count:
        raise ValueError("unreachable nodes in tree")
    return depth, order


def _pick_sample_counts(tree: _Tree, depth: list[int], encoders) -> list[float] | None:
    """Identifies the sample-count encoder structurally (mirror of the Rust side):
    the path-length encoder maps every leaf to depth + 1; the counts one is the other."""
    if not encoders:
        return None
    candidates = [
        (keys, vals)
        for keys, vals in encoders
        if not all(vals[i] == float(depth[k] + 1) for i, k in enumerate(keys))
    ]
    if len(candidates) != 1:
        raise ValueError("cannot identify the sample-count leaf encoder")
    keys, vals = candidates[0]
    counts = [float("nan")] * len(tree.feature)
    for k, v in zip(keys, vals):
        if not tree.is_leaf[k]:
            raise ValueError("leaf encoder key is not a leaf")
        if v < 1.0 or v != int(v):
            raise ValueError("sample count is not a positive integer")
        counts[k] = float(v)
    for i, leaf in enumerate(tree.is_leaf):
        if leaf and math.isnan(counts[i]):
            raise ValueError("leaf without a sample count")
    return counts


def _compute_expectations(tree: _Tree, depth, order, counts: list[float] | None) -> None:
    weight = [0.0] * len(tree.feature)
    for node in reversed(order):  # children before parents
        if tree.is_leaf[node]:
            n = counts[node] if counts is not None else 1.0
            weight[node] = n
            tree.expected[node] = float(depth[node]) + (
                average_path_length(n) if counts is not None else 0.0
            )
        else:
            t, f = tree.true_child[node], tree.false_child[node]
            weight[node] = weight[t] + weight[f]
            tree.expected[node] = (
                weight[t] * tree.expected[t] + weight[f] * tree.expected[f]
            ) / weight[node]


def load_forest(path: str) -> Forest:
    """Extracts every TreeEnsembleRegressor tree (plus leaf sample counts where the
    graph carries them) from an ONNX model."""
    graph = onnx.load(path).graph
    trees: list[_Tree] = []
    n_features = 0
    tree_nodes = [n for n in graph.node if n.op_type == "TreeEnsembleRegressor"]
    if not tree_nodes:
        raise ValueError("no TreeEnsembleRegressor node in graph")
    for node in tree_nodes:
        mapping = _column_mapping(graph, node)
        if mapping is not None:
            # The Gather mapping is the model's input contract: it sets the width
            # even when no tree splits on the last columns (mirror of the Rust side).
            n_features = max(n_features, len(mapping))
        encoders = _leaf_encoders(graph, node)
        attrs = _attr_map(node)
        if any(attrs["nodes_missing_value_tracks_true"].ints):
            raise ValueError("missing_value_tracks_true is set")
        tree_ids = list(attrs["nodes_treeids"].ints)
        node_ids = list(attrs["nodes_nodeids"].ints)
        modes = [s.decode() for s in attrs["nodes_modes"].strings]
        features = list(attrs["nodes_featureids"].ints)
        values = list(attrs["nodes_values"].floats)
        true_ids = list(attrs["nodes_truenodeids"].ints)
        false_ids = list(attrs["nodes_falsenodeids"].ints)

        multi_tree = any(t != tree_ids[0] for t in tree_ids)
        start = 0
        n = len(node_ids)
        while start < n:
            end = start
            while end < n and tree_ids[end] == tree_ids[start]:
                end += 1
            count = end - start
            tree = _Tree(
                feature=[-1] * count,
                threshold=[0.0] * count,
                true_child=[0] * count,
                false_child=[0] * count,
                is_leaf=[False] * count,
                expected=[0.0] * count,
            )
            for i in range(start, end):
                nid = node_ids[i]
                if modes[i] == "LEAF":
                    tree.is_leaf[nid] = True
                elif modes[i] == "BRANCH_LEQ":
                    column = mapping[features[i]] if mapping is not None else features[i]
                    tree.feature[nid] = column
                    tree.threshold[nid] = values[i]
                    tree.true_child[nid] = true_ids[i]
                    tree.false_child[nid] = false_ids[i]
                    n_features = max(n_features, column + 1)
                else:
                    raise ValueError(f"unsupported node mode {modes[i]!r}")
            depth, order = _structure(tree)
            counts = _pick_sample_counts(tree, depth, [] if multi_tree else encoders)
            _compute_expectations(tree, depth, order, counts)
            trees.append(tree)
            start = end
    return Forest(trees=trees, n_features=n_features)


def attribute(forest: Forest, x) -> tuple[list[float], float, float]:
    """Returns (contributions, depth, expected_depth) — see the module docstring.

    `x` is cast to float32 first so threshold comparisons see exactly the values the
    Rust side (and the model) see.
    """
    x = np.asarray(x, dtype=np.float32)
    contributions = [0.0] * forest.n_features
    depth_sum = 0.0
    expected_sum = 0.0
    for tree in forest.trees:
        expected_sum += tree.expected[0]
        node = 0
        while not tree.is_leaf[node]:
            feature = tree.feature[node]
            # NaN compares false and takes the false branch, as in the Rust walk.
            nxt = (
                tree.true_child[node]
                if x[feature] <= np.float32(tree.threshold[node])
                else tree.false_child[node]
            )
            contributions[feature] += tree.expected[nxt] - tree.expected[node]
            node = nxt
        depth_sum += tree.expected[node]
    n = len(forest.trees)
    return [-c / n for c in contributions], depth_sum / n, expected_sum / n
